#ifndef __E_OPTIMIZATION_RESULT_FORMULA_MQH__
#define __E_OPTIMIZATION_RESULT_FORMULA_MQH__

enum ENUM_OPTIMIZATION_RESULT_FORMULA {
	OPTIMIZATION_BY_PERFORMANCE,
	OPTIMIZATION_BY_DRAWDOWN,
	OPTIMIZATION_BY_RISK_REWARD,
	OPTIMIZATION_BY_WIN_RATE,
	OPTIMIZATION_BY_R_SQUARED,
	OPTIMIZATION_BY_TRADES,
	OPTIMIZATION_BY_RECOVERY_FACTOR
};

#endif
