#ifndef __E_ORDER_STATUSES_MQH__
#define __E_ORDER_STATUSES_MQH__

enum ENUM_ORDER_STATUSES {
	ORDER_STATUS_QUEUED,
	ORDER_STATUS_PENDING,
	ORDER_STATUS_OPEN,
	ORDER_STATUS_CLOSING,
	ORDER_STATUS_CLOSED,
	ORDER_STATUS_CANCELLED
};

#endif
