#ifndef __E_TRADING_PAUSE_REASON_MQH__
#define __E_TRADING_PAUSE_REASON_MQH__

enum ENUM_TRADING_PAUSE_REASON {
	TRADING_PAUSE_REASON_NONE,
	TRADING_PAUSE_REASON_MANUAL_CLOSE,
	TRADING_PAUSE_REASON_HORIZON_API_REQUEST,
	TRADING_PAUSE_REASON_ACCOUNT_INACTIVE
};

#endif
