#ifndef __E_HEARTBEAT_EVENT_MQH__
#define __E_HEARTBEAT_EVENT_MQH__

enum ENUM_HEARTBEAT_EVENT {
	HEARTBEAT_INIT,
	HEARTBEAT_DEINIT,
	HEARTBEAT_ONLINE,
	HEARTBEAT_START_DAY,
	HEARTBEAT_START_HOUR,
	HEARTBEAT_ERROR
};

#endif
