#ifndef __CONSTANTS_CO_HORIZON_GATEWAY_MQH__
#define __CONSTANTS_CO_HORIZON_GATEWAY_MQH__

#define LOG_SYSTEM_HORIZON5_GATEWAY_SERVICE "horizon5-gateway-service"
#define EVENT_POLL_INTERVAL_SECONDS 3
#define MAX_EVENTS_PER_POLL 10

#endif
