#ifndef __CONSTANTS_CO_HORIZON_MONITOR_MQH__
#define __CONSTANTS_CO_HORIZON_MONITOR_MQH__

#define LOG_SYSTEM_HORIZON5_MONITOR_SERVICE "horizon5-monitor-service"
#define API_ORDER_PATH_PREFIX "api/v1/order"
#define HORIZON_MONITOR_POLL_INTERVAL_MILLISECONDS 100
#define HEARTBEAT_INTERVAL_SECONDS 3600

#endif
