#ifndef __CONSTANTS_CO_ORDER_MQH__
#define __CONSTANTS_CO_ORDER_MQH__

#define MAX_RETRY_COUNT_OPEN   3
#define MAX_RETRY_COUNT_CANCEL 3
#define MAX_RETRY_COUNT_CLOSE  3

#define CANCEL_VALIDATION_RETRY_DEFER_SECONDS 30
#define EXPIRED_ORDER_THRESHOLD_SECONDS 3600

#define ORDER_TYPE_ANY -1
#define ORDER_STATUS_ANY -1

#define ORDER_COMMENT_PREFIX "HRZ"
#define ORDER_COMMENT_SHORT_ID_LENGTH 8

#endif
