#ifndef __E_SE_DB_OPERATOR_MQH__
#define __E_SE_DB_OPERATOR_MQH__

enum ENUM_SE_DB_OPERATOR {
	SE_DB_OP_EQUALS,
	SE_DB_OP_NOT_EQUALS,
	SE_DB_OP_GREATER_THAN,
	SE_DB_OP_LESS_THAN,
	SE_DB_OP_GREATER_THAN_OR_EQUAL,
	SE_DB_OP_LESS_THAN_OR_EQUAL,
	SE_DB_OP_CONTAINS
};

#endif
